AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  golang-testing

  Sample SAM Template for golang-testing

Parameters:
  StageName:
    Type: String
    Default: develop
    AllowedValues:
      - develop
      - prod
    Description: "Deployment stage name."

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  # API Gateway
  GolangServiceApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  GolangFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello-world/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
            ApiId: !Ref GolangServiceApi

  GetAllFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: get-all/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /all
            Method: GET
            ApiId: !Ref GolangServiceApi

Outputs:
  GolangTestingApi:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${GolangServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
