name: "Run Lambda Tests"
description: "Build and Run tests for Lambda service"

inputs:
  service_path:
    description: "Path to the location of the lambda service"
    required: true

runs:
  using: "composite"
  steps:
    # Build service
    - name: Build service
      working-directory: ${{ inputs.service_path }}
      run: sam build --parallel --cached

    # Preparing and running tests
    - name: Install dependencies for tests
      working-directory: ${{ inputs.service_path }}
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Run tests
      working-directory: ${{ inputs.service_path }}
      run: |
        python -m unittest discover -s tests -p "test*.py" -v
