AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This service contains all apis related to auth and user management.

Parameters:
  StageName:
    Type: String
    Description: Stage of app deployment (develop, prod)
    Default: prod
  LayerStackName:
    Type: String
    Description: Name of the stack where the layer is deployed
    Default: layers
  JwtSecretName:
    Type: String
    Description: Name of the secret in Secrets Manager that contains the JWT secret
    Default: python-lambda-app/prod/jwt-secret
  ThirdPartyClientsSecretName:
    Type: String
    Description: Name of the secret in Secrets Manager that contains the third party clients secrets
    Default: python-lambda-app/prod/third-party-secrets
  SecretsRegionName:
    Type: String
    Description: Region name where the secrets are stored
    Default: eu-central-1

Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  UsersApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "UsersApi-${StageName}"
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: false

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "users-${StageName}"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambdas
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: healthcheck/
      Handler: app.lambda_handler
      Runtime: python3.12
      Layers:
        - !ImportValue
          Fn::Sub: "${LayerStackName}-${StageName}-CommonLayerArn"
      Architectures:
        - x86_64
      Events:
        HealthCheckEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref UsersApi

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: login/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
          JWT_SECRET_NAME: !Ref JwtSecretName
          SECRETS_REGION_NAME: !Ref SecretsRegionName
      Layers:
        - !ImportValue
          Fn::Sub: "${LayerStackName}-${StageName}-CommonLayerArn"
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
                - "secretsmanager:GetSecretValue"
              Resource: "*"
      Events:
        LoginEndpoint:
          Type: Api
          Properties:
            Path: /login
            Method: POST
            RestApiId: !Ref UsersApi

Outputs:
  UsersApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${UsersApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
