name: "Common Setup"
description: "Checkout and setup environment for builds"

inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  aws_region:
    description: "AWS Region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Install Golang Swaggo/swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
      shell: bash

    - name: Install Python boto3
      run: pip install boto3
      shell: bash
